Repository mina-gwak/todo-list, pull requests merged in 2022-04, with the labels that each got.

#2 [COMMON] ISSUE, PR 템플릿 작성 ∙ README 작성
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: docs, common

#7 Feature/action layer
  db.json
  index.html
  src/client/js/api/actionApi.js
  src/client/js/api/index.js
  src/client/js/app.js
  src/client/js/components/ActionLayer.js
  src/client/js/components/Header.js
  src/client/js/core/Component.js
  src/client/js/store/ActionStore.js
  src/client/js/store/store.js
  src/client/js/utils/index.js
  src/client/style/style.scss
  src/server/middleware.js
  webpack.config.cjs
Labels: feat, Jamie

#11 [REVIEW] 액션 레이어 생성
  db.json
  index.html
  src/client/js/api/actionApi.js
  src/client/js/api/index.js
  src/client/js/app.js
  src/client/js/components/ActionLayer.js
  src/client/js/components/Card.js
  src/client/js/components/Column.js
  src/client/js/components/Header.js
  src/client/js/core/Component.js
  src/client/js/store/ActionStore.js
  src/client/js/store/store.js
  src/client/js/utils/index.js
  src/client/style/style.scss
  src/server/middleware.js
  webpack.config.cjs
Labels: feat

#12 [Jamie] 컬럼, 카드 렌더링
  index.html
  src/client/js/api/columnApi.js
  src/client/js/api/taskApi.js
  src/client/js/app.js
  src/client/js/components/ActionLayer.js
  src/client/js/components/Card.js
  src/client/js/components/Column.js
  src/client/js/render/index.js
  src/client/js/store/actionStore.js
  src/client/js/store/columnStore.js
  src/client/js/store/index.js
  src/client/js/store/taskStore.js
Labels: feat, Jamie
